Controllers/SanyiDeptController.cs
using Microsoft.AspNetCore.Mvc;

namespace syDeptStatus.Controllers
{
    [Route("sy/[action]")]
    public class SanyiDeptController : Controller
    {        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SanYi()
        {
            return View();
        }

        public IActionResult QualityData()
        {
            return View();
        }
    }
}

Views/SanyiDept/QualityData.cshtml
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width" />

<link rel="stylesheet" href="\lib\bootstrap-3.3.7-dist\css\bootstrap.css" />

<link rel="stylesheet" href="\lib\bootstrap-table\bootstrap-table.css" />
<link rel="stylesheet" href="\lib\bootstrap-datetimepicker\css\bootstrap-datetimepicker.css" />
<link rel="stylesheet" href="\lib\bootstrap-3.3.7-dist\css\bootstrap-theme.css" />

<script src="/lib/jquery-3.3.1.js"></script>

<script src="\lib\antv\g2\dist\g2.min.js"></script>
<script src="\lib\antv\data-set\dist\data-set.min.js"></script>
<script src="\lib\bootstrap-3.3.7-dist\js\bootstrap.js"></script>
<script src="\lib\bootstrap-table\bootstrap-table.js"></script>
<script src="\lib\bootstrap-datetimepicker\js\bootstrap-datetimepicker.js"></script>
<script src="\lib\bootstrap-datetimepicker\js\locales\bootstrap-datetimepicker.zh-CN.js"></script>

<script src="\lib\tableExport-master\tableExport.js" type="text/javascript"></script>
<script src="\lib\tableExport-master\libs\FileSaver\FileSaver.min.js" type="text/javascript"></script>
<script type="text/javascript" src="\lib\tableExport-master\libs\js-xlsx\xlsx.core.min.js"></script>

<div class=" container">
    <div>
        <h1>检验平均等待时间</h1>
    </div>
    <div class="row">
        <div class="col-sm-4">
            <div class="col-sm-2">起</div>
            <div class="col-sm-10"><input type="text" id="datetimepickerstart" class="form-control" /></div>
            
        </div>
        <div class="col-sm-4">
                <div class="col-sm-2">止</div>
                <div class="col-sm-10"><input type="text" id="datetimepickerend" class="form-control" /></div>
            
        </div>
        <div class="col-sm-4">
            <button type="button" id="lisOkBtn" class="btn btn-default" onclick="getLisChecktimeData()" >查询</button>
            <button type="button" id="exportLisBtn" class="btn btn-default" onclick="expTable()" >导出数据</button>
        </div>
    </div>
    <div class="row">
        <table id="lisdatatable" class="table table-condensed "></table>
    </div>
</div>


<script>
    $("#datetimepickerstart").datetimepicker({
        format: 'yyyy-mm-dd',
        language: 'zh-CN',
        startView: 3,
        minView: 2,
        todayBtn: true
    });
    $("#datetimepickerend").datetimepicker({
        format: 'yyyy-mm-dd',
        language: 'zh-CN',
        startView: 3,
        minView: 2,
        todayBtn: true
    });
    function getLisChecktimeData(){
        var startDate = $("#datetimepickerstart").val();
        var endDate = $("#datetimepickerend").val();
        if(startDate==""||endDate==""||endDate<startDate){
            alert("开始时间或停止时间有误");
            return;
        }
        $("#lisOkBtn").html("查询中...");
        $.ajax({
        url: "/api/sy/LisAvgData?startdate="+startDate+"&enddate="+endDate,
        type: 'GET',
        sync: true,
        success: function (data) {
            var dataobj = JSON.parse(data);
            $("#lisdatatable").bootstrapTable({
                data: dataobj,
                height: 650,
                sortable: true,
                pagination: true,
                pageSize: 50,
                pageList: [50,100,200,1000],
                columns: [{
                    field: 'PATIENT_TYPE',
                    title: '病人类型'
                }, {
                    field: 'TEST_ORDER_NAME',
                    title: '项目'
                }, {
                    field: 'PEOPLE_AMOUNT',
                    title: '人数',
                    sortable: true
                }, {
                    field: 'AVGTIME',
                    title: '平均时间',
                    sortable: true
                }]
            });
            $("#lisdatatable").bootstrapTable('load', dataobj);
            $("#lisdatatable").bootstrapTable('refresh');
            $("#lisOkBtn").html("OK");
        }
    });
    }
    

    function expTable(){
        $("#lisdatatable").tableExport(
            {
                type:'xlsx',
                fileName: '导出数据'
            }
        );
    }
</script>

Views/SanyiDept/SanYi.cshtml
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width" />

<link rel="stylesheet" href="\lib\bootstrap-4.0.0-dist\css\bootstrap.css">
<link rel="stylesheet" href="\lib\bootstrap-table\bootstrap-table.css">

<script src="/lib/jquery-3.3.1.js"></script>

<script src="\lib\antv\g2\dist\g2.min.js"></script>
<script src="\lib\antv\data-set\dist\data-set.min.js"></script>
<script src="\lib\bootstrap-4.0.0-dist\js\bootstrap.bundle.js"></script>
<script src="\lib\bootstrap-4.0.0-dist\js\bootstrap.js"></script>
<script src="\lib\bootstrap-table\bootstrap-table.js"></script>


<div class="container-fluid">
    <div class="row">
        <div>
            <h1>临床路径情况</h1>
        </div>
    </div>
    <div>
        日期:<input name="DateMonth" id="CpDate" placeholder="201801" />
        <button id="cpbtn" type="button" class="btn btn-default" onclick="cpbtnclick()">OK</button>
    </div>
    <div class="row alert alert-secondary">
        <div class="col-6 ">
            <table id="cptable" class="table table-condensed alert alert-primary"></table>
        </div>
        <div class="col-6">
            <div id="mountNode"></div>
        </div>
    </div>
    <div class="row">
        <h1>三医疑似问题反馈</h1>
    </div>
    <div>
        查看目前填写情况
    </div>
    <div>
        日期:<input name="SyDateMonth" id="SyDate" placeholder="201801" />.
        <button id="sybtn" type="button" class="btn btn-default" onclick="sybtnclick()">OK</button>
    </div>
    <div class="row">
        <div class="col-6">
            <table id="sytable" class="table table-condensed"></table>
        </div>
    </div>
    <div>
        <div>
            <h1>每月疑似问题</h1>
        </div>
        <div class="row">
            <input id="IssueAmountBtn" type="button" class="btn btn-default" value="点击查看" onclick="IssueAmountBtnClick()" />
        </div>
        <div class="row">
            <div id="nodeIssueAmount" class="col-4"></div>
            <div id="nodeIssueAmountTotal" class="col-4"></div>
            <div id="nodeIssueAmountPercent" class="col-4"></div>
        </div>
    </div>

</div>

<script>
    var chart = new G2.Chart({
        container: 'mountNode',
        forceFit: true,
        height: 400,
        padding: [20, 100, 70, 50]
    });

    function cpbtnclick() {
        var cpdate = $('#CpDate').val();
        var insl = []; //加工后的数据数组

        $.ajax({
            url: "/api/sy/cpstatics?cpdate=" + cpdate,
            type: 'GET',
            sync: false,
            success: function (data) {
                var dataobj = JSON.parse(data);
                $('#cptable').bootstrapTable({
                    data: dataobj,
                    height: 400,
                    rowStyle: function (row, index) {
                        return {
                            css: {
                                "font-size": "12px"
                            }
                        };
                    },
                    columns: [{
                        field: 'IN_SL',
                        title: '点入人数'
                    }, {
                        field: 'DISCHARGE_SL',
                        title: '当月科室出院人数'
                    }, {
                        field: 'DEPT_NAME',
                        title: '科室'
                    }, ]
                });
                $('#cptable').bootstrapTable('load', dataobj);
                $('#cptable').bootstrapTable('refresh');


                dataobj.forEach(element => {
                    var tempinsl = {
                        "DEPT_NAME": element.DEPT_NAME,
                        "TYPE": "IN",
                        "SL": element.IN_SL
                    };
                    var tempdissl = {
                        "DEPT_NAME": element.DEPT_NAME,
                        "TYPE": "DISCHARGE",
                        "SL": element.DISCHARGE_SL
                    };
                    insl.push(tempdissl);
                    insl.push(tempinsl);
                });
                console.log(insl);

                chart.source(insl);
                chart.scale('SL', {
                    alias: '人次'
                });

                chart.axis('DEPT_NAME', {
                    label: {
                        offset: 20,
                        rotate: 70,
                        textStyle: {
                            fontSize: 10,
                        }
                    }
                });
                chart.axis('SL', {});

                chart.legend({
                    position: 'right-center'
                });
                chart.interval().position('DEPT_NAME*SL').color('TYPE', ['#0050b3', '#f14193']).opacity(1);
                chart.render();
            }
        });
    }

    function sybtnclick() {
        var sydate = $('#SyDate').val();

        $.ajax({
            url: "/api/sy/syrplstatic?sydate=" + sydate,
            type: 'GET',
            sync: false,
            success: function (data) {
                var dataobj = JSON.parse(data);
                $('#sytable').bootstrapTable({
                    data: dataobj,
                    height: 600,
                    pagination: true,
                    pageSize: 15,
                    pageList: [15, 30, 50],
                    rowStyle: function (row, index) {
                        return {
                            css: {
                                "font-size": "12px"
                            }
                        };
                    },
                    columns: [{
                            field: 'TRANS_DEPT',
                            title: '转科'
                        }, {
                            field: 'ISSUE_TYPE_NAME',
                            title: '类型'
                        }, {
                            field: 'DOCTOR_IN_CHARGE',
                            title: '主管'
                        },
                        {
                            field: 'FACT',
                            title: '事实'
                        }, {
                            field: 'RESULT',
                            title: '结论'
                        }
                    ]
                });
                $('#sytable').bootstrapTable('load', dataobj);
                $('#sytable').bootstrapTable('refresh');
            }
        });

    }

    // 疑似数量图表声明
    var IssueAmountChart = new G2.Chart({
        container: 'nodeIssueAmount',
        forceFit: true,
        height: 350,
        padding: [20, 100, 70, 50]
    });
    var IssueAmountChartTotal = new G2.Chart({
        container: 'nodeIssueAmountTotal',
        forceFit: true,
        height: 350,
        padding: [20, 100, 70, 50]
    });
    var IssueAmountChartPercent = new G2.Chart({
        container: 'nodeIssueAmountPercent',
        forceFit: true,
        height: 350,
        padding: [20, 100, 70, 50]
    });

    function IssueAmountBtnClick() {
        var monthArray = [];
        var totalArray = [];
        $.ajax({
            url: "/api/sy/getissueamount",
            type: 'GET',
            sync: false,
            success: function (data) {
                var dataobj = JSON.parse(data);

                var ds = new DataSet({
                    state: {
                        currentState: 'SA'
                    }
                });
                var dv = ds.createView().source(dataobj);
                var dvTotal = ds.createView().source(dataobj);
                var dvPercent = ds.createView().source(dataobj);

                dvTotal
                    .transform({
                        type: 'aggregate',
                        fields: ['SL'],
                        operations: ['sum'],
                        as: ['TOTALSL'],
                        groupBy: ['IMPORT_DATE']
                    }) //分组后进行求和
                console.log(dvTotal);


                // dv
                // .transform({
                //     type: 'partition',
                //     groupBy: ['IMPORT_DATE']
                // })//根据月份进行分组
                // .transform({
                //     type: 'aggregate',
                //     fields:['SL'],
                //     operations: ['sum'],
                //     as: ['TOTALSL'],
                //     groupBy: ['IMPORT_DATE']
                // })//分组后进行求和
                // .transform({
                //     type: 'fold',
                //     fields: ['SL','ISSUE_TYPE'],
                //     key: 'key',
                //     value: 'SL',
                //     retains: ['IMPORT_DATE','TOTALSL']
                // })

                console.log(dv);

                IssueAmountChart.source(dv);
                IssueAmountChart.scale('SL', {
                    alias: '数量'
                });

                IssueAmountChart.axis('IMPORT_DATE', {
                    label: {
                        offset: 20,
                        rotate: 70,
                        textStyle: {
                            fontSize: 10,
                        }
                    }
                });
                IssueAmountChart.axis('SL', {
                    tickLine: {
                        length: 10
                    }
                });
                IssueAmountChart.legend({
                    position: 'right-center'
                });
                // IssueAmountChart.line().shape('smooth').position('IMPORT_DATE*TOTALSL').opacity(0.9);
                IssueAmountChart.interval().position('IMPORT_DATE*SL').color('ISSUE_TYPE', ['#40a9ff',
                    '#1890ff', '#096dd9', '#0050b3'
                ]).opacity(0.9);
                IssueAmountChart.render();

                IssueAmountChartTotal.source(dvTotal);
                IssueAmountChartTotal.scale('TOTALSL', {
                    alias: '总数量',
                    min: 100
                });
                IssueAmountChartTotal.axis('IMPORT_DATE', {
                    label: {
                        offset: 30,
                        // rotate: 70,
                        textStyle: {
                            // fontSize: 10,
                        }
                    }
                });
                IssueAmountChartTotal.axis('TOTALSL', {});
                IssueAmountChartTotal.legend({
                    position: 'right-center'
                });
                IssueAmountChartTotal.line().position('IMPORT_DATE*TOTALSL').opacity(1);
                IssueAmountChartTotal.render();


                //渲染分类百分比图
                dvPercent
                // .transform({
                //     type:'percent',
                //     field: 'SL',
                //     dimension: 'IMPORT_DATE',
                //     groupBy: ['ISSUE_TYPE'],
                //     as: 'percent'
                // });
                .transform({
                    type:'partition',
                    groupBy: 'ISSUE_TYPE'
                })
                .transform({
                    type:'percent',
                    field: 'SL',
                    dimension: 'ISSUE_TYPE',
                    // groupBy: 'ISSUE_TYPE',
                    as : 'percent'
                })
                console.log(dvPercent);
                IssueAmountChartPercent.source(dvPercent);
                IssueAmountChartPercent.scale('percent', {
                    alias: '数量'
                });

                // IssueAmountChartPercent.axis('IMPORT_DATE', {
                //     label: {
                //         offset: 20,
                //         rotate: 70,
                //         textStyle: {
                //             fontSize: 10,
                //         }
                //     }
                // });
                // IssueAmountChartPercent.axis('SL', {
                //     tickLine: {
                //         length: 10
                //     }
                // });
                IssueAmountChartPercent.coord('theta');
                IssueAmountChartPercent.tooltip({
                    showTitle: false
                });
                // IssueAmountChart.line().shape('smooth').position('IMPORT_DATE*TOTALSL').opacity(0.9);
                IssueAmountChartPercent.intervalStack().position('SL').color('ISSUE_TYPE').opacity(0.9);
                IssueAmountChartPercent.render();
            }
        })
    }
</script>

Views/SanyiDept/index.cshtml
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width" />

<link rel="stylesheet" href="\lib\bootstrap-4.0.0-dist\css\bootstrap.css">

<script src="\lib\antv\g2\dist\g2.min.js"></script>
<script src="\lib\antv\data-set\dist\data-set.min.js"></script>
<script src="\lib\bootstrap-4.0.0-dist\js\bootstrap.bundle.js"></script>
<script src="\lib\bootstrap-4.0.0-dist\js\bootstrap.js"></script>


@Html.ActionLink("三医监管相关数据","SanYi","SanyiDept",null, new {@class="btn btn-primary"} )

@Html.ActionLink("质控相关数据","qualitydata","SanyiDept",null,new {@class="btn btn-primary"} )